InfuseAI/primehub-controller

- config.yaml.example
- main.go
- pkg/graphql/spawn.go
mount job pod's working dir to emptyDir.
> mount working dir to emptyDir

- controllers/phjob_controller.go
> job cancellation

- controllers/imagespec_controller.go
`updateTime` format should be `2006-01-02T15:04:05Z`, without millisecond. Controller should correct the format.
> Correct update time format

- controllers/phjob_controller.go
Fix create pod failed, should move it into failed phase
> fix create pod failed move into failed phase

- controllers/phjob_controller.go
- controllers/phjob_scheduler.go
- pkg/escapism/escapism.go
- pkg/escapism/escapism_test.go
fix bug when username contains invalid format for label
> fix bug when username contains invalid format for label

- controllers/phjob_controller.go
- controllers/phjob_scheduler.go
- pkg/escapism/escapism.go
- pkg/escapism/escapism_test.go
Original implementation cannot handle some situations, EX: first letter is uppercase. So need to add prefix.
> fix bug for label

- controllers/phjob_controller.go
- pkg/graphql/spawn.go
Fix
1. project volume should be lowercase
2. same dataset information may show multiple times when query graphql => this is a quick fix, a comprehensive fix will be introduced later.
> quick fix for testing in demo a

- config/crd/bases/primehub.io_imagespecjobs.yaml
- config/crd/bases/primehub.io_imagespecs.yaml
- config/crd/bases/primehub.io_phjobs.yaml
- config/samples/primehub_v1alpha1_phjob.yaml
- controllers/phjob_controller.go
- main.go
- pkg/graphql/spawn.go
this MR allow to set nodSelector, tolerations, affinity in the config.yaml for operator to run the pod in the specific nodes.
> allow to customize nodSelector, tolerations, affinity

- pkg/graphql/spawn.go
- pkg/graphql/spawn_test.go
dataset should be "not writable" if it is mounted because of the dataset is "global" or "not lunch group only"
> Fix dataset writable readable logic

- controllers/phjob_controller.go
Fix the issue
https://app.clubhouse.io/infuseai/story/6581/phjob-controller-make-the-primehub-controller-crashloopbackoff
> fix crashloop by ttl handling

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/ISSUE_TEMPLATE/failing-test.md
- .github/ISSUE_TEMPLATE/support-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Add CONTRIBUTING.md.
- Add issue templates (bug/feature request/support request/pull
request).
Signed-off-by: Aaron Huang <aaroms9733@gmail.com>
> Add CONTRIBUTING.md and github template for issue.

- controllers/phjob_scheduler.go
Fix bug.
The user quota is calculated based on a group.
Fix user quota calculation bug.
No
```release-note
NONE
```
> Fix user quota should be calculated based on group

- api/v1alpha1/phjob_types.go
- controllers/phjob_controller.go
- controllers/phjob_scheduler.go
Refactor phjob reason and message field logic
The current logic in phjob reason and message field is not consistent with k8s convention
Update phjob reason and message field
No
```release-note
None
```
> Update phjob reason and message field to follow k8s convention

- api/v1alpha1/phjob_types.go
- config/crd/bases/primehub.io_phjobs.yaml
- controllers/phjob_controller.go
- controllers/phjob_scheduler.go
- controllers/phjob_scheduler_test.go
Feature change
ch7134
```release-note
The phase name changes from ready to preparing
```
> Change phjob phase naming: ready to preparing [ch7134]

- controllers/phjob_controller.go
feature
this PR make pod name as phjob name so it is not confused
as above
```release-note
None
```
> make pod name as phjob name

- controllers/phjob_scheduler.go
- pkg/graphql/spawn.go
Signed-off-by: popcorny <celu@infuseai.io>
**PR checklist**
Feature
https://app.clubhouse.io/infuseai/story/6918/add-env-variables-for-the-user-and-group-of-the-running-job
https://app.clubhouse.io/infuseai/story/7140/phjob-scheduler-group-info-and-instance-type-cache-time-change-from-10m-to-1m
Please see the screenshots here
https://app.clubhouse.io/infuseai/story/6918/add-env-variables-for-the-user-and-group-of-the-running-job#activity-7542
```release-note
```
> Add env variables for the user and group of the running job

- controllers/imagespecjob_controller.go
- ee/main.go
- main.go
Story details: https://app.clubhouse.io/infuseai/story/7680
> Size of ephemeral storage for image builder should be configurable

- api/v1alpha1/phschedule_types.go
- config/crd/bases/primehub.io_phschedules.yaml
- config/samples/primehub_v1alpha1_phschedule.yaml
Update the CRD definition per discussion on 2/21
> Define Job schedule CRD

- scripts/custom_image/build-and-push.sh
Story details: https://app.clubhouse.io/infuseai/story/8234
Set USER env if it exists in base image
> Set USER env according to base image

- controllers/phschedule_controller.go
- pkg/graphql/graphql.go
feature
to sync timezone every 10 min and change the cron timezone
```release-note
None
```
> sync timezone every 10 min and change the cron timezone

- controllers/phschedule_controller.go
feature
phschedule change reconcile to 1min
if instancetype, user, group, etc change, it needs 10 min to reflect it
```release-note
None
```
> phschedule change reconcile to 1min

- controllers/imagebuilder_test.go
- controllers/imagespec_controller_test.go
- controllers/suite_test.go
Story details: https://app.clubhouse.io/infuseai/story/6332
Add a basic controller test for ImageSpec
> minimum test including functional and state change

- ee/main.go
- main.go
Story details: https://app.clubhouse.io/infuseai/story/8554
> Increase default ephemeral storage size to 30Gi

- api/v1alpha1/phdeployment_types.go
- config/crd/bases/primehub.io_phdeployments.yaml
Signed-off-by: popcorny <celu@infuseai.io>
Fix the wrong CRD. Add predictor in deployment spec.
```release-note
```
> Add CRD and sample for phdeployment

- controllers/imagespecjob_controller.go
Story details: https://app.clubhouse.io/infuseai/story/8492
> Swap the order of pip and conda install

- pkg/graphql/spawn.go
Fix a bug
Add support of the hostpath dataset
Hostpath datasets are not worked in jobs
No
```release-note
NONE
```
> Fix the bug jobs cannot mount hostpath dataset

- Dockerfile
- Dockerfile.ee
* Fix ci, we forget to copy seldon api files into docker image
> Copy seldon api to image

- pkg/graphql/spawn.go
Modify job submission workingdir mount path to /home/jovyan
> Modify job submission workingdir mount path to /home/jovyan

- Dockerfile
- Dockerfile.ee
bug
remove copy seldon api in Dockerfile
```release-note
None
```
> remove copy seldon api

- ee/controllers/phdeployment_controller.go
bug
add prefix "deploy-" to deployment 
```release-note
None
```
> add prefix deploy- to the deployment name

- ee/controllers/phdeployment_controller.go
bug
Add prefix to deploymentKey for curl deployment
```release-note
None
```
> Add prefix to deploymentKey for curl deployment

- ee/controllers/phjob_controller.go
Bug
Fix the timezone in the job container to match system setting
```release-note
none
```
> Add TZ env to fix timezone in the job container

- ee/controllers/phdeployment_controller.go
bug
should scale up deployment after redploy the phDeployment from stop phase
```release-note
None
```
> fix scale up deployment after redeploying

- ee/config/crd/bases/primehub.io_phdeployments.yaml
- ee/controllers/phdeployment_controller.go
- ee/main.go
- pkg/graphql/graphql.go
When primehub-controller try to create phDeployment, the controller will check the group `enabledDeployment` flag from graphql. If the selected group doesn't enable Model Deployment, the controller will throw an error message `The model deployment is not enabled for the selected group` at the status of the phDeployment.
Model deployment feature
```release-note
```
> Model deployment controller check is group enable model deployment

- ee/controllers/phdeployment_controller.go
- ee/pkg/license/const.go
- pkg/graphql/spawn.go
- pkg/graphql/spawn_test.go
adjust pod resources for the model deployments
To fit  resource constraint, we need to consider both of model and container's resource.
ch9018
> Make deployment to fit the resource constraint

- ee/controllers/phdeployment_controller.go
- ee/main.go
bug
use primehubURL from helm value in the endpoint rather than hardcoded
```release-note
None
```
> Use primehuburl from helm value in the endpoint

- ee/controllers/imagebuilder_test.go
- ee/controllers/imagespec_controller.go
- ee/main.go
Story details: https://app.clubhouse.io/infuseai/story/9264
> [Image Builder] Modify primehub-controller logic: allow empty image builder configs

- ee/controllers/phdeployment_controller.go
bug
add image pull secret to the deployment
```release-note
None
```
> add image pull secrets

- ee/pkg/license/license.go
- ee/pkg/license/license_test.go
Signed-off-by: Ash Wu <hsatac@infuseai.io>
Co-authored-by: Timothy Lee <ctiml@infuseai.io>
Fix license expiry check.
Future license should be considered unexpired, not expired.
> Fix license expiry check

- pkg/graphql/graphql.go
- pkg/graphql/spawn.go
- pkg/graphql/spawn_test.go
Feature
Support hostpath and nfs dataset in jobs.
> jobs support hostpath and nfs dataset type

- ee/controllers/phdeployment_controller.go
- ee/main.go
Feature request
Let the image of EnginerContainer in PHDeployment is configurable.
Use to support the airgap environment.
```release-note
NONE
```
> [Feature] ch8993 phdeployment support configurable engine image setting

- ee/controllers/phjob_controller.go
feature
mount volume for shared memory
```release-note
None
```
> mount volume for shared memory

- ee/controllers/phdeployment_controller.go
- ee/controllers/phdeployment_controller_test.go
- ee/controllers/testutil.go
- pkg/graphql/spawn.go
1. refactor the reconcile logic
2. fix bugs
- container restart should change the status from Failed to Deployed
- change instanceType should redeploy deployment
- if disable model deployment, should change the status to failed and release the resources
3. add unit test
```release-note
None
```
> refactor reconcile logic, fix bugs and add unit tests for update status

- ee/controllers/phdeployment_controller.go
refactor
refactor the update deployment logic
so it is only updated when the spec is changed by users
```release-note
None
```
> refactor update deployment logic

- ee/controllers/phdeployment_controller.go
feature
Add annotation to get the client name from ingress
```release-note
None
```
> Add annotation to get the client name from ingress

- ee/controllers/phdeployment_controller.go
Signed-off-by: popcorny <celu@infuseai.io>
```release-note
```
> handle the case that annotation last-applied-configuration is missing

- ee/controllers/phjob_controller.go
- ee/controllers/phschedule_controller.go
- ee/go.sum
- ee/main.go
- go.mod
- go.sum
- pkg/graphql/graphql_test.go
- pkg/graphql/spawn.go
Feature
Add phfs to every jobs when the store function enabled
```release-note
None
```
> Add mount phfs when store enable

- ee/api/v1alpha1/phdeployment_types.go
- ee/config/crd/bases/primehub.io_phdeployments.yaml
Feature
We want to have an update message for phdeployment.
```release-note
None
```
> Add updateMessage field into the phdeployment

- ee/controllers/phdeployment_controller.go
- go.mod
- go.sum
> fix update stale object status bug and inherit instancetype properties

- ee/controllers/phdeployment_controller.go
- ee/controllers/phjob_controller.go
Feature added
Add usage metadata 
https://app.clubhouse.io/infuseai/story/11373/add-usage-annotation-to-related-components-job-jupyter-deployment
> Add usage annotations

- pkg/graphql/spawn.go
- pkg/graphql/spawn_test.go
Bug
Make env dataset work in bash
```release-note
None
```
> Fix env dataset for bash

- ee/controllers/phdeployment_controller.go
Bugfix
The model deployment image pull policy should be always
```release-note
```
> [Fix] ch11440 set model deployment image pull policy to always

- ee/main.go
Signed-off-by: Ash Wu <hSATAC@gmail.com>
Allow pass config via env
So we can use 12 factor style in k8s deployment
> Allow pass config via env

- ee/controllers/phjob_scheduler.go
Signed-off-by: ericy <ericy@infuseai.io>
```release-note
```
> phjobs: change to failed state if group info not found

- ee/controllers/phjob_controller.go
Bugfix
Avoid phJob failed when a pod has been created
ch11074
> Ignore phJob pod already created

- ee/controllers/phjob_controller.go
Feature
For submitting a function as a job, we need some additional envs.
```release-note
None
```
> Add envs to job

- ee/controllers/phdeployment_controller.go
> update component name

- ee/controllers/phjob_controller.go
- ee/controllers/phjob_scheduler.go
- ee/main.go
- pkg/graphql/graphql.go
Feature 
Jobs can config timeout
```release-note
```
> Add job timeout config in group

- ee/controllers/phjob_cleaner.go
- ee/main.go
> Add clean up completed jobs feature

- ee/controllers/license_controller.go
- ee/controllers/phjob_controller.go
- ee/main.go
- ee/scripts/job/run-job.sh
- pkg/graphql/spawn.go
Feature
Enable sudo for job submission
```release-note
```
> Add GRANT_SUDO to enable sudo for job submission

- ee/scripts/job/run-job.sh
bugfix
When calls the `exec` command inside the bash script, it will change the current shell environment and return directly when the exec command completed.
```release-note
```
> [Fix] ch13705 fix job artifacts failed to upload issue

- config.yaml.example
- ee/controllers/phjob_controller.go
- ee/main.go
- ee/scripts/job/run-job.sh
- pkg/graphql/spawn.go
Story details: https://app.clubhouse.io/infuseai/story/12303
> Implement the artifact retention

- config.yaml.example
- ee/controllers/phjob_controller.go
- ee/main.go
- ee/scripts/job/run-job.sh
Feature Added
inject monitoring-agent around job execution
ch13360
```release-note
Support hardware utilization monitoring
```
> Run monitoring-agent around job execution

- pkg/graphql/spawn.go
Story details: https://app.clubhouse.io/infuseai/story/13811
> [Bug] Cannot run job when artifact and phfs are not enabled

- config.yaml.example
- ee/api/v1alpha1/phdeployment_types.go
- ee/config/crd/bases/primehub.io_phdeployments.yaml
- ee/controllers/phdeployment_controller.go
- ee/main.go
Feature
phdeployment controller support model uri
```release-note
None
```
> Add phdeployment controller support model uri

- ee/api/v1alpha1/phdeployment_types.go
- ee/config/crd/bases/primehub.io_phdeployments.yaml
- ee/controllers/phdeployment_controller.go
- ee/controllers/phjob_controller.go
Feature
Add Env in PhDeployment CRD and pass the env to model deployment
```release-note
```
> [Feature] ch13326 implement phdeployment support environment variables

- ee/controllers/phdeployment_controller.go
bugfix
add gpu resources to model container
ch13562
```release-note
Bugfix: fix PhDeployment ignores GPU resources
```
> Add GPU resources to model container

- ee/controllers/phdeployment_controller.go
bugfix
we got panic by a nil deployment
ch14354
> Fix crash by nil deployment

- ee/controllers/imagespecjob_controller.go
- ee/scripts/custom_image/build-and-push.sh
> [Feature] ch14311 controller use env SKIP_TLS_VERIFY for buildah script

- ee/controllers/phjob_controller.go
- pkg/graphql/graphql.go
Feature
Notify job events to graphql
```release-note
```
> Add notify job events to graphql

- CONTRIBUTING.md
- DEVELOP.md
Signed-off-by: Ash Wu <hSATAC@gmail.com>
doc
> Add DEVELOP.md

- ee/api/v1alpha1/license_types.go
- ee/config/crd/bases/primehub.io_licenses.yaml
- ee/controllers/license_controller.go
- Add max_model_deploy field
- Provide default values for all int fields
- Change all type int to *int
> Primehub-controller support max_node and max_model_deploy

- ee/scripts/job/run-job.sh
Co-authored-by: Poga Po <poga.po@gmail.com>
Feature added
Job submission support PrimeHub profile to setup group runtime variables
ch15689
> Implementation PrimeHub profile

- DEVELOP.md
Update document
Install kubebuilder correctly on Apple M1 Device.
```release-note
```
> [Update] Develop document to support Apple M1 Device

- ee/controllers/phdeployment_controller.go
feature added
export port 6000 for the model's custom metrics feature 
https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html#metrics-endpoints
ch16280
> Support custom metrics port

- ee/main.go
Bug fixed
Allow `/feedback` uri working
ch16280
Reference:
Feedback method is not handled in the engine's REST API #1825
https://github.com/SeldonIO/seldon-core/issues/1825
> Upgrade seldon-core-executor to 1.4.0

- pkg/graphql/spawn.go
Bug fix
The deployment env will be override by dataset env
ch15951
```release-note
```
> [Fix] fix env be overrided by dataset env

- controllers/phapplication_controller.go
- controllers/phapplication_controller_test.go
- ee/controllers/phjob_scheduler.go
- ee/controllers/phjob_scheduler_test.go
- pkg/quota/resourceQuota.go
> [Feature] ch15951 Implement the phapplication controller - abnormal cases

- api/v1alpha1/phapplication_types.go
- api/v1alpha1/phapptemplate_types.go
- config/crd/bases/primehub.io_images.yaml
- config/crd/bases/primehub.io_imagespecjobs.yaml
- config/crd/bases/primehub.io_imagespecs.yaml
- config/crd/bases/primehub.io_phapplications.yaml
- config/crd/bases/primehub.io_phapptemplates.yaml
- go.mod
Co-authored-by: Even Wei <evenwei@infuseai.io>
Feature
Support rewrite when proxy
```release-note
```
> Add rewrite field into phapplication and phapptemplate

- controllers/phapplication_controller.go
- controllers/phapplication_controller_test.go
- pkg/cache/cache.go
- pkg/graphql/graphql.go
- pkg/graphql/spawn.go
Bug fix
- Apply global datasets when creating deployment
- Set workdir when enabling group volume
ch16623
```release-note
```
> [Fix] ch16623 fix global datasets not apply when create deployment

- pkg/graphql/spawn.go
Bug fix
- The datasets are not sorted after graphql query. Need to sort them before applying them into volume mount.
ch16623
```release-note
```
> [Fix] ch16623 sort datasets after graphql query

- api/v1alpha1/phapplication_types.go
- controllers/phapplication_controller.go
- controllers/phapplication_controller_test.go
- ee/controllers/phjob_controller.go
- ee/controllers/phschedule_controller.go
- ee/main.go
- main.go
- pkg/graphql/graphql_test.go
- pkg/graphql/spawn.go
- pkg/graphql/spawn_test.go
Bug fix
- Don't configure working dir
- Create symlink under PRIMEHUB_APP_ROOT not working dir
ch16655
```release-note
```
> [Fix] ch16655 add phfs into the deployment of phapplication

- pkg/graphql/spawn.go
Feature
- phApplication deployment will use initContainer to apply PRIMEHUB_APP_ROOT folder
ch16669
```release-note
```
> [Feature] ch16669 add init-container in phApplication deployment

- pkg/graphql/spawn.go
Bug
Fix bug
```release-note
```
> Fix volume mount name

- controllers/imagespecjob_controller.go
Bugfix
Prevent injection by filtering illegal packages
```release-note
```
> Filter illegal packages

- pkg/graphql/spawn.go
- Fix duplicated envvars
- Fix env datasets conflict with phapp env
Signed-off-by: Ash Wu <hSATAC@infuseai.io>
> Fix phapp env related issues

- ee/controllers/phjob_controller.go
- pkg/graphql/graphql.go
Feature added
Add mlflow configurations
ch16762
**to reviewers**
* controller image `ch16762-18839d`
* It works with graphql `ch16758-4d1013e0`
This PR should merge after *ch16758* release
----
setting example:
> Add mlflow envs to the PhJob pod

- controllers/phapplication_controller.go
Co-authored-by: Ash Wu <hsatac@gmail.com>
feature added: `app` component
add ph-application to the usage report
ch15954
> Add primehub.io/usage annotation to PhApplication

- config.yaml.example
- controllers/phapplication_controller.go
- controllers/phapplication_controller_test.go
- ee/main.go
- main.go
- pkg/graphql/spawn.go
Enchantment
Add 2 preset variables
ch17227
Add new configuration section:
```yaml
primehubUrl: http://example.primehub.io
```
> Introduce PRIMEHUB_URL and PRIMEHUB_GROUP to PhApplication

- config.yaml.example
- ee/controllers/phdeployment_controller.go
- ee/controllers/phdeployment_controller_test.go
- ee/controllers/phjob_controller.go
- ee/main.go
- pkg/graphql/graphql.go
Feature added
handle modelUri `models:/<model-name>/<version-number>`
ch16771
* The controller relies on the new helm-chart https://github.com/InfuseAI/primehub/pull/316
* image tag `ch16771-da796a`
> Support mlflow-model-downloader

- pkg/graphql/spawn.go
bugfix
fix pod resource settings
ch17567
* we follow the jupyterhub_profiles: only set the limits for `GPU`
> Fix GPU resources

- ee/main.go
Co-authored-by: Ash Wu <hsatac@gmail.com>
bugfix
remove feature flag for model deployment
ch17980
> Always enable modelDeployment

- controllers/imagespecjob_controller.go
Enhancement
Extract buildJob image config and upgrade buildah version
```release-note
```
> Extract buildJob image config and upgrade buildah version

- ee/controllers/phdeployment_controller.go
- ee/controllers/phdeployment_controller_test.go
Feature Added
support `nfs://` to modelUri
ch18018
image tag `ch18018-56b15e`
> Support NFS Volume for deployment

- ee/controllers/phdeployment_controller.go
> Add rbac for event api

- ee/scripts/custom_image/build-and-push.sh
Bugfix
Can skip tls verify when pulling image
```release-note
```
> Pulling image can skip tls verify

- ee/scripts/custom_image/build-and-push.sh
Hotfix
Can skip tls verify for all buildah steps
```release-note
```
> Apply --tls-verify to buildah bud command

- api/v1alpha1/phapplication_types.go
- api/v1alpha1/phapptemplate_types.go
- config/crd/bases/primehub.io_phapplications.yaml
- config/crd/bases/primehub.io_phapptemplates.yaml
- controllers/phapplication_controller.go
- pkg/graphql/spawn.go
Co-authored-by: Ash Wu <hsatac@infuseai.io>``
Feature
Support customize app root
```release-note
```
> Support customize app root

- api/v1alpha1/imagespecjob_types.go
- config/crd/bases/primehub.io_imagespecjobs.yaml
- controllers/image_controller.go
- controllers/imagespec_controller.go
- controllers/imagespecjob_controller.go
Feature
Support single repository
```release-note
```
> Support single repo

- .circleci/config.yml
Signed-off-by: Eric Chang <ericcc@infuseai.io>
Chore 
To see the coverage impact from PR, and overview of current coverage
Upload coverage report to CodeCov
```release-note
NONE
```
> Add CodeCov to PrimeHub-Controller

- .circleci/config.yml
Signed-off-by: Eric Chang <ericcc@infuseai.io>
Chore 
gomodules.xyz/jsonpatch/v2@v2.0.1 is not available
Update golang version to 1.15
```release-note
NONE
```
> update circleci image to 1.15

- Dockerfile
- Dockerfile.ee
Signed-off-by: Eric Chang <ericcc@infuseai.io>
Chore 
gomodules.xyz/jsonpatch/v2@v2.0.1 is not available
Update image version to 1.15.15
```release-note
NONE
```
> update Docker image to 1.15.15

- config.yaml.example
WHY:
Change resource from gcr.io to Dockerhub
HOW:
Change config yaml example file.
Signed-off-by: simonliu <simon3458@gmail.com>
- [X ] Ensure you have added or ran the appropriate tests for your PR.
- [X ] DCO signed
Change version
Change resource from gcr.io to Dockerhub.
sc-26877
N/A
```release-note
Change kfserving-storage-initializer resource from gcr.io to Dockerhub.
```
> Change model storage initializer repository.

- ee/controllers/phdeployment_controller.go
- pkg/graphql/spawn.go
Bugfix
Fix model image url with leading or trailing whitespace
> [PH-22] Fix model image url with leading or trailing whitespace

- controllers/image_controller.go
- controllers/imagespecjob_controller.go
Bugfix
Fix image build state not synced
> [PH-2] Fix image build state not synced

- ee/controllers/phdeployment_controller_test.go
- ee/controllers/phjob_controller.go
- ee/main.go
- pkg/email/email.go
- pkg/graphql/graphql.go
Feature
Add email notifications
> [PH-27] Job Email Notifications

- ee/controllers/phdeployment_controller.go
- ee/controllers/types.go
Bugfix
Fix deployment ingress class name
> [Bug] Fix deployment ingress class name
